### ISSUE TITLE
CD for ava-issue-handler and closing issues automatically

### ISSUE THREAD

**Issue by binaryPUNCH** [awslabs/amazon-virtual-andon#1]
Hi. First of all thanks for this solution. Having a lot of fun trying it out at LEGO together with shopfloor colleagues.

1. If I would like to make some minor adjustments to the ava-issue-handler Lambda function, how do I deploy it? The preconfigured codecommit -> codepipeline seems to only deploy the frontend with Amplify. Should I bundle a zip myself and upload on the console?

2. I succeeded in raising issues in an automated fashion when a PLC tag reads an error code. Now I need to close issues automatically when the error code goes back to zero. How would you recommend doing this? It seems I need the complete random ID before I can close, so I need to do a quick query before a mutate on UpdateIssue is possible? If I wanted to extend the AppSync-schema and add a mutation to simply close all issues for a particular device, how would I go about doing so?

**Comment by binaryPUNCH** [comment]
1. I guess there is just no pipeline for this. I see the package.json has some run-scripts for building and zipping. Albeit Linux only, I used it as inspiration to do it on my own with a manual upload to update the Lambda code.

2. I learned about GraphQL/Appsync and looked into the existing resolvers. It seems quite complex with the VTL so as opposed to extending the schema with a new mutation, I will simply use the existing schema and first `issuesByDevice` query before `updateIssue` mutation. Howevver, it would be nice to have an easy way of closing an issue without needing to know the ID of the particular event.

**Comment by beomseoklee** [comment]
Thanks for contacting us @binaryPUNCH 

For your questions, 
1. you can download the source code from GitHub, and when you make a change, you can build the source code and deploy the zip file to Lambda function.
2. Do you use Amazon Virtual Andon UI to raise issues and update issue or you are sending messages to IoT topic directly? In either case, if you want to close every issues related to a specific device, as you mentioned, you might need to call GraphQL APIs several times or update (or create) the resolver.

Also, we've updated this solution to v2.0.0, so if you are interested in the latest version, you can deploy the new stack with the latest template which provides more flexibility to update the solution. You can refer to the latest information [here](https://docs.aws.amazon.com/solutions/latest/amazon-virtual-andon/welcome.html).
